### ISSUE TITLE
[Question] Unembedded replies

### ISSUE THREAD

**Issue by A-Beille** [WillTDA/Discord.js-Akinator#39]
Hey !
Is it possible to use the api without MessageEmbed ? I say using the api with only plain replies, and not Embeds.
And can we edit the embed, like edit some words in the description or the title ?

**Comment by WillTDA** [comment]
Hello! Due to the simplistic design of the package, this will not be a feature I will be adding.

The only way you can do this is to create a private version of the package for only yourself, and then edit the code that way. 👍
