### ISSUE TITLE
Moderate issue with got version

### ISSUE THREAD

**Issue by DiamondPRO02** [WillTDA/Discord.js-Akinator#41]
I have discordjs bot that runs the newest akinator version 4.0.1 and I keep seeing this error.
Is there or will there be a fix for this?
![image](https://user-images.githubusercontent.com/53056204/192214803-36a939c4-fb75-4d89-9d90-5689a6c4da74.png)

**Comment by WillTDA** [comment]
Hello 👋 Thanks for bringing this to my attention. I'll be sure to check for any updates to the package before publishing the next release (which should be released in a few days). I'll keep this issue open until then. 😃

**Comment by WillTDA** [comment]
I have updated all of Discord.js Akinator's dependencies to their latest versions. However, even the latest release of `@vitalets/google-translate-api`, the package Akinator uses to translate extra information, uses vulnerable versions of `got` it's HTTP request library.

Seeing as `@vitalets/google-translate-api` has not been updated in 7 months, I will make a fork and update the code myself.

**Comment by DiamondPRO02** [comment]
Yeah, it shouldn't. I'm just annoyed by it. XD
Thank you
