### ISSUE TITLE
Package does not work properly anymore

### ISSUE THREAD

**Issue by DodoGames7** [WillTDA/Discord.js-Akinator#43]
When using the latest version of djs-akinator v4, this Error will appear upon trying to start the game.
![image](https://user-images.githubusercontent.com/69091682/236662007-3d41c78e-caa9-4abf-9f34-1d734f88e74d.png)
It appears that aki-api package (which is what this packages uses) no longer works with v6 considering that it hasn't being updated for two years (according to their [issues](https://github.com/jgoralcz/aki-api/issues) page), and so many people are starting to have the same problem. Is there any idea on how we can use discord.js-akinator package now?

**Comment by WillTDA** [comment]
Hello! 👋 The API does still work, however as of right now its intermediate certificates have been installed incorrectly.

To install these yourself and fix the problem temporarily:

1) Install `node_extra_ca_certs_mozilla_bundle` from NPM.
2) Add the following to the top-most part of your code (**ensuring that this runs before anything else**):
```js
const fs = require('fs');
const https = require('https');
https.globalAgent.options.ca = fs.readFileSync('node_modules/node_extra_ca_certs_mozilla_bundle/ca_bundle/ca_intermediate_root_bundle.pem');
```

If the problem with the API is not resolved on its own soon, I will consider making a patch which implements the above solution.

Thank you for opening an issue! 😄

**Comment by DodoGames7** [comment]
Interesting, will try that.

**Comment by DodoGames7** [comment]
It worked, the game seemed to be very slow to me but that could be my host resources being low. Thanks for the fix tho, i kinda recommend patching that if possible. Other than that, thank you very much!

**Comment by DodoGames7** [comment]
Looks like aki-api has been updated. I guess the patch is no longer needed?

**Comment by WillTDA** [comment]
Thanks for letting me know! I'll look into it.

**Comment by DodoGames7** [comment]
np, aki-api version 6.0.9 seems to fix this now

**Comment by WillTDA** [comment]
Upon inspection of the new `aki-api` patch, it looks like the author has implemented the exact same patch that I had proposed a week ago.

I also proposed this solution over on the package's [issue page](https://github.com/jgoralcz/aki-api/issues/143#issuecomment-1537365343), so maybe I influenced this release, who knows!

I'll be updating to use this new version in the next few days. 👍

**Comment by DodoGames7** [comment]
Alright! Thanks for information. (Sorry for late response)
